## POSTTEST 7 Kecerdasan Buatan
Nama : Krisdayanti

NIM : 2009106064

Kelas : KB B1'20

In [1]:
import tensorflow as tf

- Membuat sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [2]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=1).numpy()

In [3]:
random_tensor

array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)

- Membuat sebuah tensor dengan shape(5,5) dengan variable prime_tensor yang berisi list nilai bilangan prima

In [4]:
prime_tensor = [[2,83,5,7,61], [13,47,19,43,29], [31,37,41,23,17], [53,59,11,71,73], [79,3,89,97,2]]
prime_tensor

prime_tensor_dimension = tf.convert_to_tensor(prime_tensor, dtype=tf.int64)

- Menampilkan dimensi dari kedua variable

In [5]:
random_tensor.shape #menampilkan dimensi variable random_tensor

(5, 5)

In [6]:
prime_tensor_dimension.shape #menampilkan dimensi variable prime_tensor_dimension

TensorShape([5, 5])

## Operator Artimetika

- Menampilkan hasil perhitungan aritmetika dari variable random_tensor dengan variable prime_tensor_dimension

1. Operator penjumlahan → tf.add()

In [7]:
tf.add(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.1886818, 84.4846   ,  5.0653296,  4.557296 , 61.099247 ],
       [13.591225 , 47.592823 , 16.877071 , 42.277103 , 28.94373  ],
       [31.643545 , 36.735676 , 42.856632 , 23.567842 , 16.617165 ],
       [51.514656 , 60.261772 , 10.974694 , 70.73537  , 74.532814 ],
       [77.25702  ,  2.562107 , 88.43399  , 97.32067  ,  3.132831 ]],
      dtype=float32)>

2. Operator pengurangan → tf.subtraction()

In [8]:
tf.subtract(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -2.8113182, -81.5154   ,  -4.9346704,  -9.442704 , -60.900753 ],
       [-12.408775 , -46.407177 , -21.122929 , -43.722897 , -29.05627  ],
       [-30.356455 , -37.264324 , -39.143368 , -22.432158 , -17.382835 ],
       [-54.485344 , -57.738228 , -11.025306 , -71.26463  , -71.467186 ],
       [-80.74298  ,  -3.437893 , -89.56601  , -96.67933  ,  -0.867169 ]],
      dtype=float32)>

3. Operator perkalian → tf.multiply()

In [9]:
tf.multiply(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  -1.6226364 ,  123.221695  ,    0.32664686,  -17.09893   ,
           6.0541525 ],
       [   7.685916  ,   27.86268   ,  -40.335663  ,  -31.084581  ,
          -1.6318411 ],
       [  19.949888  ,   -9.77999   ,   76.12196   ,   13.060359  ,
          -6.50821   ],
       [ -78.7232    ,   74.444496  ,   -0.27836686,  -18.788708  ,
         111.89541   ],
       [-137.69519   ,   -1.3136789 ,  -50.37489   ,   31.10492   ,
           2.265662  ]], dtype=float32)>

4. Operator pembagian → tf.divide()

In [10]:
tf.divide(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.4056591 ,  0.01788673,  0.01306587, -0.34895775,  0.00162702],
       [ 0.04547879,  0.01261325, -0.11173314, -0.01681156, -0.00194036],
       [ 0.02075951, -0.00714389,  0.04528373,  0.02468877, -0.02251976],
       [-0.02802535,  0.02138595, -0.00230055, -0.00372718,  0.02099745],
       [-0.022063  , -0.14596431, -0.00635966,  0.00330587,  0.5664155 ]],
      dtype=float32)>

5. Operator pangkat → tf.pow()

In [11]:
tf.pow(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 6.58237278e-01,  1.75208292e+14,  1.18998764e-06,
        -5.18914917e+02,  0.00000000e+00],
       [ 1.07839960e-03,  2.12557298e-11, -1.62845650e+06,
        -8.71549673e-07, -5.72948387e-37],
       [ 1.16397109e-06, -4.15966456e-22,  1.04176673e+11,
         2.22447557e-06, -8.15107839e-08],
       [-1.27886054e+09,  9.07514625e+05, -2.72567179e-18,
        -0.00000000e+00,  3.47317018e+13],
       [-1.15356923e+19, -8.39660764e-02, -1.00310215e-22,
         0.00000000e+00,  1.28330600e+00]], dtype=float32)>

6. Operator logaritma → tf.math.log()

In [12]:
tf.math.log(random_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[        nan,  0.39514455, -2.7283134 ,         nan, -2.3101294 ],
       [-0.5255598 , -0.52285945,         nan,         nan,         nan],
       [-0.44076362,         nan,  0.61876476, -0.5659126 ,         nan],
       [        nan,  0.23251635,         nan,         nan,  0.42710513],
       [        nan,         nan,         nan, -1.1373451 ,  0.12471979]],
      dtype=float32)>

## Tensor Statistics Collection (Min & Max)

- Menampilkan nilai maksimal dan minimal dari variable random_tensor

Nilai maksimal

In [13]:
tf.argmax(random_tensor, axis = 0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 0, 2, 2, 3], dtype=int64)>

Nilai minimal

In [14]:
tf.argmin(random_tensor, axis = 0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([4, 4, 1, 0, 2], dtype=int64)>

## Concatenation

- Menampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor

In [15]:
concated_sample_1 = tf.concat([random_tensor, prime_tensor], axis=0)
print("Size of the Concatenated Data :", concated_sample_1)

Size of the Concatenated Data : tf.Tensor(
[[-8.1131822e-01  1.4845988e+00  6.5329373e-02 -2.4427042e+00
   9.9248402e-02]
 [ 5.9122431e-01  5.9282297e-01 -2.1229296e+00 -7.2289723e-01
  -5.6270380e-02]
 [ 6.4354479e-01 -2.6432407e-01  1.8566332e+00  5.6784171e-01
  -3.8283589e-01]
 [-1.4853433e+00  1.2617711e+00 -2.5306080e-02 -2.6462969e-01
   1.5328138e+00]
 [-1.7429771e+00 -4.3789294e-01 -5.6601000e-01  3.2066926e-01
   1.1328310e+00]
 [ 2.0000000e+00  8.3000000e+01  5.0000000e+00  7.0000000e+00
   6.1000000e+01]
 [ 1.3000000e+01  4.7000000e+01  1.9000000e+01  4.3000000e+01
   2.9000000e+01]
 [ 3.1000000e+01  3.7000000e+01  4.1000000e+01  2.3000000e+01
   1.7000000e+01]
 [ 5.3000000e+01  5.9000000e+01  1.1000000e+01  7.1000000e+01
   7.3000000e+01]
 [ 7.9000000e+01  3.0000000e+00  8.9000000e+01  9.7000000e+01
   2.0000000e+00]], shape=(10, 5), dtype=float32)


## Tensor Sorting

- Menampilkan hasil sorting dari variable random_tensor dan prime_tensor secara descending

In [16]:
tf.argsort(random_tensor, direction="DESCENDING")

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[1, 4, 2, 0, 3],
       [1, 0, 4, 3, 2],
       [2, 0, 3, 1, 4],
       [4, 1, 2, 3, 0],
       [4, 3, 1, 2, 0]])>

In [17]:
tf.argsort(prime_tensor, direction="DESCENDING")

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[1, 4, 3, 2, 0],
       [1, 3, 4, 2, 0],
       [2, 1, 0, 3, 4],
       [4, 3, 1, 0, 2],
       [3, 2, 0, 1, 4]])>